// <auto-generated />
using System;
using EstateAgency.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstateAgency.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123192039_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EstateAgency.Domain.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CounterpartyId")
                        .HasColumnType("int")
                        .HasColumnName("counterparty_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<int>("RealEstateId")
                        .HasColumnType("int")
                        .HasColumnName("real_estate_id");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("transaction_amount");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartyId");

                    b.HasIndex("RealEstateId");

                    b.ToTable("applications");
                });

            modelBuilder.Entity("EstateAgency.Domain.Entities.Counterparty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("full_name");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("passport_number");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("counterparties");
                });

            modelBuilder.Entity("EstateAgency.Domain.Entities.RealEstate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("CadastralNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cadastral_number");

                    b.Property<double>("CeilingHeight")
                        .HasColumnType("double")
                        .HasColumnName("ceiling_height");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int")
                        .HasColumnName("floor_number");

                    b.Property<int>("FloorsTotal")
                        .HasColumnType("int")
                        .HasColumnName("floors_total");

                    b.Property<bool>("HasEncumbrances")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_encumbrances");

                    b.Property<int>("Purpose")
                        .HasColumnType("int")
                        .HasColumnName("purpose");

                    b.Property<int>("Rooms")
                        .HasColumnType("int")
                        .HasColumnName("rooms");

                    b.Property<double>("TotalArea")
                        .HasColumnType("double")
                        .HasColumnName("total_area");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("real_estates");
                });

            modelBuilder.Entity("EstateAgency.Domain.Entities.Application", b =>
                {
                    b.HasOne("EstateAgency.Domain.Entities.Counterparty", "Counterparty")
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstateAgency.Domain.Entities.RealEstate", "RealEstate")
                        .WithMany()
                        .HasForeignKey("RealEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counterparty");

                    b.Navigation("RealEstate");
                });
#pragma warning restore 612, 618
        }
    }
}
